services:
  - type: web
    name: ipl-auction-app
    env: node
    plan: free
    buildCommand: "pnpm install && pnpm run build"
    startCommand: "pnpm run start"
    envVars:
      - key: NODE_VERSION
        value: 20
